# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCadastro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastro(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1853, 1053)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("leticia")
    self.driver.find_element(By.NAME, "email").send_keys("leticia@email")
    self.driver.find_element(By.NAME, "password").send_keys("12345")
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("12345")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("leticia@email.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "formBasicEmail").click()
    self.driver.find_element(By.ID, "formBasicEmail").send_keys("leticia")
    self.driver.find_element(By.ID, "formBasicPassword").send_keys("12345")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-graduation-cap").click()
    self.driver.find_element(By.LINK_TEXT, "Perfil").click()
  
