# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestRevisor():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_revisor(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1853, 1053)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-in-alt").click()
    self.driver.find_element(By.ID, "formBasicEmail").click()
    self.driver.find_element(By.ID, "formBasicEmail").send_keys("gabi")
    self.driver.find_element(By.ID, "formBasicPassword").send_keys("12345")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Sair").click()
    self.driver.find_element(By.LINK_TEXT, "Entrar").click()
    element = self.driver.find_element(By.LINK_TEXT, "Entrar")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Clique aqui").click()
    self.driver.find_element(By.ID, "formBasicEmail").click()
    self.driver.find_element(By.ID, "formBasicEmail").send_keys("gabi")
    self.driver.find_element(By.ID, "formBasicPassword").send_keys("12345")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .row > .row > .card:nth-child(1) > .btn").click()
    assert self.driver.switch_to.alert.text == "Deseja realizar esta revisão?"
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.XPATH, "(//textarea[@id=\'originalText\'])[2]").click()
    self.driver.find_element(By.XPATH, "(//textarea[@id=\'originalText\'])[2]").send_keys("Bom texto")
    self.driver.find_element(By.CSS_SELECTOR, ".radio-inline:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.switch_to.alert.text == "Revisão enviada com sucesso!"
    self.driver.switch_to.alert.accept()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt > path").click()
  
